name: My First GitHub Actions Workflow

on: 
  push:

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hi
        run: echo "Hi"

  say-bye:
    runs-on: ubuntu-latest
    steps:
      - name: Say Bye
        run: echo "Bye"

